version: '3.8'
services:
  web:
    image: myapp:latest
    build: .
    ports:
      - "8080:80"
    environment:
      - APP_ENV=production
      - DATABASE_URL=mysql://user:password@localhost:3306/mydatabase
    volumes:
      - .:/app
    networks:
      - mynetwork

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  dbdata:
